name: SISSAdmin
options:
  bundleIdPrefix: com.siss
targets:
  SISSAdmin:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Models
      - path: Network
      - path: Utils
      - path: ViewModels
      - path: Views
      - path: SISSAdminApp.swift
    info:
      path: Info.plist